<?php
/**
 * @file
 * Get currency rate from nbrb and store it in variables.
 */

/**
 * Implements hook_help();
 */
function nbrb_rate_help($path, $arg) {
  switch ($path) {
    case 'admin/help#nbrb_rate':{
      $ret_val = '<h3>' . t('About') . '</h3>';
      $ret_val .= '<p>' . t('This module gets oficial todays currency rates established by National Bank of the Republic of Belarus and store it in global variables.') . '</p>';
      return $ret_val;
      break;
    }
  }
}

/**
 * Implements hook_permission().
 */
function nbrb_rate_permission() {
  return array(
    'administer nbrb rate' => array(
      'title' => t('Administer NBRB rate'),
      'description' => t('Change configurations for NBRB rate'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function nbrb_rate_menu() {
  // Admin configuration group.
  $items['admin/config/nbrb_rate'] = array(
    'title' => 'NBRB Rate',
    'description' => 'Administer NBRB Rate',
    'access arguments' => array('administer nbrb rate'),
  );
  
  // Admin configuration - Settings.
  $items['admin/config/nbrb_rate/manage'] = array(
    'title' => 'NBRB Rate settings',
    'description' => 'Manage NBRB Rate settings and configurations',
    'access arguments' => array('administer nbrb rate'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nbrb_rate_settings_form'),
  );
  return $items;
}

/**
 * Implements hook_form().
 */
function nbrb_rate_settings_form($node, &$form_state) {
  $form['overview'] = array(
    '#markup' => t('This interface allows administrators manage general NBRB Rate settings'),
    '#prefix' => '<p>',
    '#suffix' => '</p>',
  );
  $form['nbrb_currency'] = array(
    '#title' => 'Choose currency',
    '#type' => 'select',
    '#description' => t('Choosen curency rate will be get as soon as cron run.'),
    '#options' => array(
      1 => 'USD',
      2 => 'EUR',
    ),
    '#default_value' => variable_get('nbrb_currency'),
  );
  
  return system_settings_form($form);
}

/**
 * Getting course rate from nbrb.by
 */
function nbrb_rate_cron() {
  $currency = variable_get('nbrb_currency');
  $rate = 0;
  $var_to_set = '';
  switch ($currency) {
    case 1:{
      $rate = 145;
      $var_to_set = 'nbrb_rate_usd';
      break;
    }
    case 2:{
      $rate = 292;
      $var_to_set = 'nbrb_rate_eur';
      break;
    }
  }
  $url = 'http://www.nbrb.by/API/ExRates/Rates/' . $rate;
  $ch = curl_init(); 
  curl_setopt($ch, CURLOPT_URL, $url); 
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
  curl_setopt($ch, CURLOPT_TIMEOUT, 1); 
  $out = curl_exec($ch); 
  $cur = json_decode($out, TRUE)['Cur_OfficialRate'];
  curl_close($ch);
  variable_set($var_to_set, $cur);
  
  // Inform user.
  drupal_set_message(t("Variable $var_to_set is set to $cur"));
}